# Generated by Django 4.2.4 on 2023-08-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='cats/cover/')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('breed', models.CharField(choices=[('siamese', 'Siamese'), ('persian', 'Persian'), ('maine_coon', 'Maine Coon'), ('ragdoll', 'Ragdoll'), ('bengal', 'Bengal'), ('sphynx', 'Sphynx'), ('abyssinian', 'Abyssinian'), ('british_shorthair', 'British Shorthair'), ('scottish_fold', 'Scottish Fold'), ('siberian', 'Siberian'), ('norwegian_forest', 'Norwegian Forest'), ('devon_rex', 'Devon Rex'), ('burmese', 'Burmese'), ('oriental', 'Oriental'), ('cornish_rex', 'Cornish Rex'), ('egyptian_mau', 'Egyptian Mau'), ('himalayan', 'Himalayan'), ('exotic_shorthair', 'Exotic Shorthair'), ('turkish_van', 'Turkish Van'), ('manx', 'Manx'), ('singapura', 'Singapura')], max_length=20)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
    ]
